CREATE SCHEMA CONTROLE AUTHORIZATION admin;

CREATE TABLE CONTROLE.users (
    id SERIAL PRIMARY KEY UNIQUE NOT NULL,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    role  VARCHAR(100) NOT NULL
);

CREATE TABLE CONTROLE.categories (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(100) NOT NULL
);


CREATE TABLE CONTROLE.expenses (
    id SERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    value_expense NUMERIC(10,2) NOT NULL,
    description VARCHAR(255),
    payment_date DATE,

    CONSTRAINT FK_EXPENSE_USER FOREIGN KEY (user_id) REFERENCES CONTROLE.users(id),
    CONSTRAINT FK_EXPENSE_CATEGORY FOREIGN KEY (category_id) REFERENCES CONTROLE.categories(id)
);

CREATE TABLE CONTROLE.payments (
    id SERIAL PRIMARY KEY,
    payment_date DATE NOT NULL,
    expense_id BIGINT NOT NULL,

    CONSTRAINT FK_PAYMENT_EXPENSE FOREIGN KEY (expense_id) REFERENCES CONTROLE.expenses(id)
);


